### ISSUE TITLE
cannot build with vite

### ISSUE THREAD

**Issue by yungxiaomcc** [minio/minio-js#1002]
I use minio.js in my vue+vite project，but when i tried to create clinet ,occured error:

_stream_readable.js:48 
       Uncaught ReferenceError: global is not defined
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require (chunk-OYVF2PGL.js?v=c8651b20:10:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require (chunk-OYVF2PGL.js?v=c8651b20:10:50)
    at node_modules/block-stream2/index.js (index.js:1:23)
    at __require (chunk-OYVF2PGL.js?v=c8651b20:10:50)
    at node_modules/minio/dist/main/minio.js (minio.js:21:43)
    at __require (chunk-OYVF2PGL.js?v=c8651b20:10:50)
    at dep:minio:1:16

and i find some useful infomation :
- https://github.com/MatrixAI/js-virtualfs/issues/4; 
- https://www.npmjs.com/package/@rollup/stream
its maybe a rollup issue

can you help me to aviod this problem ?(not very smooth english, sry ^-^)

**Comment by Luca8991** [comment]
I'm getting the exact same error with vanilla-ts + vite

**Comment by yuhaozhai** [comment]
same

**Comment by cfmj** [comment]
same error

**Comment by prakashsvmx** [comment]
Please refer to https://github.com/minio/minio-js/issues/1053#issuecomment-1196291784 and make adjustments as per the module bundler documentation

**Comment by cfmj** [comment]
> 我用 vanilla-ts + vite 得到了完全相同的错误

Have you solved the problem?

**Comment by cfmj** [comment]
> I'm getting the exact same error with vanilla-ts + vite

Have you solved the problem?

**Comment by lmq352489099** [comment]
Vite support Minio client now ? 0.0
