### ISSUE TITLE
WebIdentityToken

### ISSUE THREAD

**Issue by ryansteakley** [minio/minio-js#1078]
Previous issue was closed, The examples given don't seem to give much explanation or insight in what needs to be done. I already know how to use minio-go and the webIdentityToken/IRSA setup there. Asking for clarification on the minio-js side.       
 From examples since none seem to use webIdentityToken it is not clear what needs to be done here? 
Do I need to pass the webIdentityToken and  the roleARN into 

```
let asRoleProvider = new AssumeRoleProvider({
    stsEndpoint: "s3.amazonaws.com",
    accessKey: 'miniojs',
    secretKey: 'miniojs123',
    webIdentityToken: '/var/secret/etc/',
    roleARN: "arn:aws:...."
})
```

For it work or will these be picked up automatically when using this AssumeRoleProvider?

_Originally posted by @ryansteakley in https://github.com/minio/minio-js/issues/1077#issuecomment-1312617914_

**Comment by prakashsvmx** [comment]
You need to obtain and pass it. It would not be picked up if specified as file. (There is no way to tell if token needs to be read from file. ).

Please provide details/trace on what was tried and error if any for further debugging which would help us better understand the issue. Appreciate your efforts to try these APIs and provide feedback.  Thank you for the support

**Comment by ryansteakley** [comment]
Thanks for the response, that gives me a path forward, will come back with any issues encountered.

**Comment by ryansteakley** [comment]
Would appreciate an example of this setup and the code to at least bare minimum create the minio-client, currently with the lack of documentation and expertise I am going through trial and error. Since you closed https://github.com/minio/minio-js/issues/841 with #960, I assume internally it was verified that this functionality works.

**Comment by prakashsvmx** [comment]
We request more information
are you using minio server? 
 how have you have configured Assume Role? 
 how was the token obtained ?

As mentioned earlier, the example initialization can be like:
```
let asRoleProvider = new AssumeRoleProvider({
    stsEndpoint:"http://127.0.0.1:9000",
    accessKey: 'miniojs',
    secretKey: 'miniojs123'

  })
    const asRoleClient= new Minio.Client({
        endPoint: 'localhost',
        port: 9000,
        useSSL: false,
        accessKey: 'miniojs',
        secretKey: 'miniojs123',
        credentialsProvider:asRoleProvider
    })

```


Feel free to share any information that would be helpful for us to debug further
 
 `AWS_WEB_IDENTITY_TOKEN_FILE` is not supported in `minio-js`

i have followed the following links while implementing.\
```
https://github.com/minio/minio/blob/master/docs/sts/assume-role.md#testing-an-example-with-awscli-tool
https://github.com/minio/minio/blob/master/docs/sts/assume-role.md#testing-an-example-with-assume-rolego
```

**Comment by ryansteakley** [comment]
The use-case is I have an eks-cluster with a pod that has `AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token` mounted along with the `AWS_ROLE_ARN:                 arn:aws:iam::111122223333:role/my-role`. I want to be able to use these two pieces of information to authenticate and create a minioClient to communicate with s3 using minio-js. This is possible using minio-go at the moment. I see you said that `AWS_WEB_IDENTITY_TOKEN_FILE` is not supported in minio-js. So if I the user write additional js code to extract the token from said `AWS_WEB_IDENTITY_TOKEN_FILE` it should be fine? Then I will go along and pass the rest of the information needed RoleArn etc..

**Comment by prakashsvmx** [comment]
I have not personally tried this approach. yes, you could try and send a pr to support AWS_WEB_IDENTITY_TOKEN_FILE

if you are using AWS, you could also use aws-sdk.

**Comment by ryansteakley** [comment]
@prakashsvmx I've tried doing 

```
let asRoleProvider = new AssumeRoleProvider({
    stsEndpoint:"sts.amazonaws.com",
    webIdentityToken: "abcdef:
    roleARN: "abcdef"

  })
    const asRoleClient= new Minio.Client({
        endPoint: 's3.amazonaws.com',
        credentialsProvider:asRoleProvider
    })
```

and I'm facing issue of  

```
(node:6818) UnhandledPromiseRejectionWarning: Error: Unable to get  credentials. Expected instance of BaseCredentialsProvider
    at Client.fetchCredentials (/Users/ryanstea/minio-js/node_modules/minio/dist/main/minio.js:3762:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.checkAndRefreshCreds (/Users/ryanstea/minio-js/node_modules/minio/dist/main/minio.js:3749:14)
```

any guidance?

**Comment by prakashsvmx** [comment]
`AWS_WEB_IDENTITY_TOKEN_FILE` based credential provider needs implementation. Feel free to send a PR.
