### ISSUE TITLE
Critical exception at listObjects

### ISSUE THREAD

**Issue by Sworroo** [minio/minio-js#1088]
Hello, I'm using minio.js 7.0.32 and MinIO: [RELEASE.2022-12-12T19-27-27Z]. When I'm trying to use listObject like so:
```    
    async getFilesList(): Promise<string[]> {
        return await new Promise((resolve, reject) => {
            const files = [] as string[];
            this.client.listObjectsV2(this.config.bucketName)
                .on("data", (object) => files.push(object.name))
                .on("error", (err) => reject(err))
                .on("end", () => resolve(files));
        });
    }
```
    
 The method returns with an error:
```
static/node_modules/minio/dist/main/helpers.js:493
  let asStrName = (objectName || "").replace(/\+/g, ' ');
                                     ^
TypeError: (objectName || "").replace is not a function
    at sanitizeObjectKey (/home/services/launchserverv2/static/node_modules/minio/dist/main/helpers.js:493:38)
    at /home/services/launchserverv2/static/node_modules/minio/dist/main/xml-parsers.js:421:53
    at Array.forEach (<anonymous>)
    at parseListObjects (/home/services/launchserverv2/static/node_modules/minio/dist/main/xml-parsers.js:420:56)
    at DestroyableTransform._flush (/home/services/launchserverv2/static/node_modules/minio/dist/main/transformers.js:98:19)
    at DestroyableTransform.prefinish (/home/services/launchserverv2/static/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (events.js:400:28)
    at prefinish (/home/services/launchserverv2/static/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/home/services/launchserverv2/static/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/home/services/launchserverv2/static/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/home/services/launchserverv2/static/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (internal/streams/readable.js:670:10)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
Thanks in advance.

**Comment by Sworroo** [comment]
I made a PR https://github.com/minio/minio-js/pull/1089
