### ISSUE TITLE
SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by badushaebrahim** [minio/minio-js#1091]
## context 
i am trying to connect to a local instance of minio container in my system to retrive a file , i have another one that uses java its working fine but here i ma getting this error 

## my code :-
`var Minio = require('minio')
const Stream = require('stream')
const express = require("express");
const app = express();
// const bodyParser= require('body-parser');
// const mongoose= require('mongoose');
const cors= require('cors');

  app.use(express.json());
//   app.use(cors({origin: 'http://localhost:3000',
//   credentials: true}));
  
  
  var port= 4545;
  //listen to the port
var minioClient = new Minio.Client({
    endPoint: 'localhost',

    useSSL:false,
    port: 9000,
    accessKey: 'ebXgd59VSBNmKEFw',
    secretKey: 'z6kTHsX7V6mwTS8gepiTPp5AH0jHUpf2f'
});
  app.get('/file/:fileId', (req, res) => {
    var size = 0
    const fileId = req.params.fileId

minioClient.getPartialObject('strm', fileId, 10, 30, function(err, dataStream) {
    if (err) {
      return console.log(err)
    }
    dataStream.on('data', function(chunk) {
      size += chunk.length
    })
    dataStream.on('end', function() {
      console.log('End. Total size = ' + size)
    })
    dataStream.on('error', function(err) {
      console.log(err)
    })
  })

  })

  app.listen(port, () => {
    console.log('Server started on port '+port);
});
  `
## Error:- 
`Server started on port 4545
S3Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Object.parseError (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\minio\dist\main\xml-parsers.js:71:11)
    at C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\minio\dist\main\transformers.js:166:22
    at DestroyableTransform._flush (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\minio\dist\main\transformers.js:90:10)
    at DestroyableTransform.prefinish (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\readable-stream\lib\_stream_transform.js:129:10)
    at DestroyableTransform.emit (node:events:526:28)
    at prefinish (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\readable-stream\lib\_stream_writable.js:611:14)
    at finishMaybe (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\readable-stream\lib\_stream_writable.js:620:5)
    at endWritable (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\readable-stream\lib\_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (C:\Users\Acabes\Desktop\streamo\streamo-streamer-ms-nodejs\node_modules\readable-stream\lib\_stream_writable.js:571:22)
    at IncomingMessage.onend (node:internal/streams/readable:693:10) {
  code: 'SignatureDoesNotMatch',
  bucketname: 'strm',
  resource: '/strm',
  requestid: '17348D0605B1681B',
  hostid: '5af6f320-2383-4a94-86c8-39bab9db452a',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
`

**Comment by prakashsvmx** [comment]
Could you please enable trace for minioClient and share the output ? also please share the minio and sdk versions used.
`minioClient.traceOn()`

**Comment by prakashsvmx** [comment]
I have tried
```javascript

var s3Client = new Minio.Client({
  endPoint: 'localhost',
  accessKey: 'minio',
  secretKey: 'minio123',
  useSSL:false,
  port:20002
})

var size = 0

let bucketName ='test-bucket'
let fileId="data.json"

// s3Client.traceOn()

s3Client.getPartialObject(bucketName, fileId, 10, 30, function(err, dataStream) {
  if (err) {
    return console.log(err)
  }
  dataStream.on('data', function(chunk) {
    size += chunk.length
  })
  dataStream.on('end', function() {
    console.log('End. Total size = ' + size)
  })
  dataStream.on('error', function(err) {
    console.log(err)
  })
})
```


The output of a sample object in MinIO:
```
 ➜ node src/test/test_sign_mismatch-1091.js
End. Total size = 30
```
Verify the object in bucket
```
➜ mc stat local2/test-bucket/data.json
Name      : data.json
Date      : 2022-12-02 16:32:31 IST 
Size      : 325 KiB 
ETag      : 2dbf0f4a239a05ea877d997bdffbcf4c 
Type      : file 
Metadata  :
  X-Amz-Meta-App: SPH-REACT-JS 
  Content-Type  : application/json 

```

if you are using any proxy or any network settings specific to your environment, please investigate
