### ISSUE TITLE
Error while uploading large files

### ISSUE THREAD

**Issue by adhi14058** [minio/minio-js#1208]
I am trying to upload a large file and I get an error mentioned below.
```javascript
  async function putObject() {
    try {
      const filePath = path.resolve(__dirname, `1GB.txt`)
      const readStream = fs.createReadStream(filePath)
      const obj = await objectStoreClient.putObject(
        bucket,
        `newFile/${Date.now()}/1GB`,
        readStream
      );
      console.log(obj)
    } catch (error) {
      console.error(error)
    }
  }
``` 

```
S3Error: The request you provided implies functionality that is not implemented.
    at Object.parseError (/home/adhi/Projects/webshop/node_modules/minio/dist/main/xml-parsers.js:64:11)
    at /home/adhi/Projects/webshop/node_modules/minio/dist/main/transformers.js:144:22
    at Transform._flush (/home/adhi/Projects/webshop/node_modules/minio/dist/main/transformers.js:77:10)
    at Transform.prefinish (/home/adhi/Projects/webshop/node_modules/minio/node_modules/readable-stream/lib/_stream_transform.js:123:10)
    at Transform.emit (node:events:513:28)
    at prefinish (/home/adhi/Projects/webshop/node_modules/minio/node_modules/readable-stream/lib/_stream_writable.js:569:14)
    at finishMaybe (/home/adhi/Projects/webshop/node_modules/minio/node_modules/readable-stream/lib/_stream_writable.js:576:5)
    at endWritable (/home/adhi/Projects/webshop/node_modules/minio/node_modules/readable-stream/lib/_stream_writable.js:594:3)
    at Writable.end (/home/adhi/Projects/webshop/node_modules/minio/node_modules/readable-stream/lib/_stream_writable.js:535:22)
    at IncomingMessage.onend (node:internal/streams/readable:705:10) {
  code: 'XNotImplemented',
  resource: '/bucket?uploads&delimiter=&max-uploads=1000&prefix=newFile%2F1694608733508%2F1GB',
  requestid: 1694608732418880,
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
``` 

On inspecting the code, I found out that the code seems to work if in the function `listIncompleteUploadsQuery`, we  change
```queries.push(`delimiter=${(0, _helper.uriEscape)(delimiter)}`); ```
to
``` if(delimiter) { queries.push(`delimiter=${(0, _helper.uriEscape)(delimiter)}`); }```

I need some help as I am not sure why this is happening.

**Comment by prakashsvmx** [comment]
Please use latest  `"minio": "^7.1.3"` . 
i just verified a 1GB file. auto/with different part sizes as well  for both `fPutObject` and `putObject`.
