### ISSUE TITLE
Error when calling the function getBucketPolicy

### ISSUE THREAD

**Issue by stilet** [minio/minio-js#1367]
Hello! Why does the following function give an error:

```
const getBucketPolicy = async (bucket: string) => {


    const list = await minioClient.getBucketPolicy(bucket);
     return list 
}
```

```
S3Error: The bucket policy does not exist
    at parseError (file:///home/leo/Projects/DEMO/S3/s3front/node_modules/.pnpm/minio@8.0.2/node_modules/minio/dist/esm/internal/xml-parser.mjs:24:13)
    at Module.parseResponseError (file:///home/leo/Projects/DEMO/S3/s3front/node_modules/.pnpm/minio@8.0.2/node_modules/minio/dist/esm/internal/xml-parser.mjs:71:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Client.makeRequestStreamAsync (file:///home/leo/Projects/DEMO/S3/s3front/node_modules/.pnpm/minio@8.0.2/node_modules/minio/dist/esm/internal/client.mjs:507:19)
    at async Client.getBucketPolicy (file:///home/leo/Projects/DEMO/S3/s3front/node_modules/.pnpm/minio@8.0.2/node_modules/minio/dist/esm/internal/client.mjs:1713:17)
    at async getBucketPolicy (/home/leo/Projects/DEMO/S3/s3front/src/routes/buckets/[slug]/+page.server.ts:19:18)
    at async load (/home/leo/Projects/DEMO/S3/s3front/src/routes/buckets/[slug]/+page.server.ts:36:20)
    at async Module.load_server_data (/home/leo/Projects/DEMO/S3/s3front/node_modules/.pnpm/@sveltejs+kit@2.9.0_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.19_vite@5.4.11_@types+node@_dvr7mjyq27fg3nhzwlhdsnnk4q/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:61:17)
    at async eval (/home/leo/Projects/DEMO/S3/s3front/node_modules/.pnpm/@sveltejs+kit@2.9.0_@sveltejs+vite-plugin-svelte@3.1.1_svelte@4.2.19_vite@5.4.11_@types+node@_dvr7mjyq27fg3nhzwlhdsnnk4q/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:156:13) {
  code: 'NoSuchBucketPolicy',
  bucketname: 'test',
  resource: '/test',
  requestid: '1810B625597AD4B8',
  hostid: 'b2dcfa6f-0d64-48e8-9071-dbb7cd0864f3',
  amzRequestid: '1810B625597AD4B8',
  amzId2: undefined,
  amzBucketRegion: undefined
```

![image1](https://github.com/user-attachments/assets/99472cdb-f9b4-4b11-b0d0-1728086ff71b)

"minio": "^8.0.2"

**Comment by prakashsvmx** [comment]
There is no issue there: the code needs to handle the error. because by default there is no bucket (anonymous) policy .

```js

const getBucketPolicy = async (bucket) => {


    try {
        const policyConf = await minioClient.getBucketPolicy(bucket);
        console.log(policyConf) 
        return list
    }catch (err){
        console.log(err.message)
    }
}

getBucketPolicy('test-bucket-1')
```

e.g:

``` json 
# No policy bucket
node index.js
The bucket policy does not exist


# bucket with anonymous policy:

node index.js
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:ListBucketMultipartUploads","s3:GetBucketLocation","s3:ListBucket"],"Resource":["arn:aws:s3:::test-bucket"]},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:DeleteObject","s3:GetObject","s3:ListMultipartUploadParts","s3:PutObject","s3:AbortMultipartUpload"],"Resource":["arn:aws:s3:::test-bucket/*"]}]}

```
