### ISSUE TITLE
Received an exception when attempting to download object

### ISSUE THREAD

**Issue by fkautz** [minio/minio-js#245]
```js
 client.getObject(bucket, 'hello', function(e, r) {
   console.log(e)
   r.pipe(process.stdout)
 })
```

```js
/source/minio.js:694
    return cb({
           ^
TypeError: Cannot read property 'pipe' of undefined
    at /home/fkautz/src/test-minio-js/index.js:86:5
    at parseError (/source/minio.js:694:12)
    at ClientRequest.<anonymous> (/source/minio.js:409:16)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:310:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by fkautz** [comment]
This now works. Closing.
