### ISSUE TITLE
Uncaught exception on localhost:9000

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#261]
~~~
$ node list-buckets.js 
undefined
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Readable.emit (events.js:87:13)
    at /source/minio.js:165:18
    at /source/xml-parsers.js:59:16
    at ConcatStream.<anonymous> (/home/harsha/node_modules/minio/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (/home/harsha/node_modules/minio/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:499:14)
    at afterWrite (/home/harsha/node_modules/minio/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at afterTick (/home/harsha/node_modules/minio/node_modules/concat-stream/node_modules/readable-stream/node_modules/process-nextick-args/index.js:11:8)
    at process._tickCallback (node.js:355:11)
~~~ 

No buckets on the server yet. 

~~~
$ node list-buckets.js 
$
~~~ 

One out of two attempts leads to correct output.

**Comment by harshavardhana** [comment]
Wrong bug.. stale 'minio' package. Closing
