### ISSUE TITLE
listObjects() exception on non-existent bucket

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#265]
~~~
$ node list.js 
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DestroyableTransform.emit (events.js:87:13)
    at DestroyableTransform.onerror (_stream_readable.js:556:12)
    at DestroyableTransform.emit (events.js:107:17)
    at onwriteError (/home/harsha/repos/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/home/harsha/repos/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/home/harsha/repos/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/home/harsha/repos/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/home/harsha/repos/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /home/harsha/repos/minio-js/test/minio.js:462:20
~~~

**Comment by harshavardhana** [comment]
~~~
var Minio = require('./minio')
var Through2 = require('through2')

var s3client = new Minio({
  url: 'http://localhost:9000',
  accessKey: 'YW9OTO0DL5O5GT6OJ3GU',
  secretKey: 'yLBGjYwHRVy341gLlZ1djwJmI4wAedV+CBKeemnH'
})

var objectsStream = s3client.listObjects('your-bucket', {
  recursive: true
})
objectsStream.pipe(Through2.obj(function(object, enc, done) {
  console.log(object)
  done()
}))
~~~

**Comment by fkautz** [comment]
The problem here is there is nothing hooked up to the error stream of the pipe. Node will throw an exception if you don't consume errors on the stream. Try this code snippet instead:

```js
var objects = client.listObjects('your-bucket', {recursive: true})
objects.pipe(Through2.obj(function(obj, enc, done) {
     done()
}))
objects.on('error', function(e) {
    console.log(e)
})
```

**Comment by harshavardhana** [comment]
I picked up list-objects.js example, we should update it then.

**Comment by fkautz** [comment]
Examples are updated.

**Comment by fkautz** [comment]
#271
