### ISSUE TITLE
Fix type errors for our custom exceptions.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#363]
```
 node remove-incomplete-upload.js

/source/minio.js:470
      throw new errors.isValidBucketNameException('Invalid bucket name: ' + bucket)
                ^
TypeError: Cannot read property 'isValidBucketNameException' of undefined
    at Client.removeIncompleteUpload (/source/minio.js:470:17)
    at Object.<anonymous> (/Users/harsha/Repositories/minio-js/dist/main/remove-incomplete-upload.js:28:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

```
$ node remove-incomplete-upload.js

/source/minio.js:476
      throw new errors.InvalidObjectNameException('Object name cannot be empty')
                ^
TypeError: Cannot read property 'InvalidObjectNameException' of undefined
    at Client.removeIncompleteUpload (/source/minio.js:476:17)
    at Object.<anonymous> (/Users/harsha/Repositories/minio-js/dist/main/remove-incomplete-upload.js:28:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by harshavardhana** [comment]
Fixing this error led to another error 

```
$ node remove-incomplete-upload.js

/source/minio.js:473
      throw new errors.isValidBucketNameException('Invalid bucket name: ' + bucket)
                                                                            ^
ReferenceError: bucket is not defined
    at Client.removeIncompleteUpload (/source/minio.js:473:77)
    at Object.<anonymous> (/Users/harsha/Repositories/minio-js/dist/main/remove-incomplete-upload.js:28:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```
