### ISSUE TITLE
One of the windows tests failed after the merge in putObject()

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#375]
```
 117 passing (13s)
  1 pending
  1 failing
 
  1) Client object level #putObject(bucket, object, source, size, contentType, callback) with large objects using multipart should fail if actual size is larger than expected:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at done (C:\projects\minio-js\node_modules\mocha\lib\runnable.js:245:13)
      at C:\projects\minio-js\node_modules\mocha\lib\runnable.js:317:7
      at C:\source\unit\test.js:935:13
      at C:\projects\minio-js\node_modules\async\lib\async.js:52:16
      at C:\projects\minio-js\node_modules\async\lib\async.js:691:30
      at C:\projects\minio-js\node_modules\async\lib\async.js:167:37
      at C:\projects\minio-js\node_modules\async\lib\async.js:1204:30
      at DestroyableTransform.<anonymous> (C:\source\minio.js:692:29)
      at DestroyableTransform.<anonymous> (C:\source\helpers.js:122:32)
 
 
 
Uncaught exception: { [Error: 1 test failed.]
  message: '1 test failed.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-mocha',
  __safety: { toString: [Function] },
  domain: 
   { domain: null,
     _events: { error: [Function: handleException] },
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! minio@0.2.9 prepublish: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minio@0.2.9 prepublish script 'gulp test'.
npm ERR! This is most likely a problem with the minio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls minio
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\minio-js\npm-debug.log
```

**Comment by harshavardhana** [comment]
Build failed again 
```

---------- Forwarded message ----------
From: AppVeyor <no-reply@appveyor.com>
Date: Fri, Dec 11, 2015 at 8:52 AM
Subject: Build failed: minio-js 137
To: harsha@harshavardhana.net


Build minio-js 137 failed

Commit fb34f78d25 by Harshavardhana on 12/11/2015 4:47 PM: 
Merge pull request #383 from krishnasrinivas/excpetion-to-error

Configure your notification preferences

``

**Comment by harshavardhana** [comment]
I think the bug is evident on windows we have to see why. 

```
 1 failing
 
  1) Client object level #putObject(bucket, object, source, size, contentType, callback) with large objects using multipart should fail if actual size is larger than expected:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at done (C:\projects\minio-js\node_modules\mocha\lib\runnable.js:245:13)
      at C:\projects\minio-js\node_modules\mocha\lib\runnable.js:317:7
      at C:\source\unit\test.js:935:13
      at C:\projects\minio-js\node_modules\async\lib\async.js:52:16
      at C:\projects\minio-js\node_modules\async\lib\async.js:691:30
      at C:\projects\minio-js\node_modules\async\lib\async.js:167:37
      at C:\projects\minio-js\node_modules\async\lib\async.js:1204:30
      at DestroyableTransform.<anonymous> (C:\source\minio.js:680:29)
      at DestroyableTransform.<anonymous> (C:\source\helpers.js:106:32)
 
 
 
Uncaught exception: { [Error: 1 test failed.]
  message: '1 test failed.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-mocha',
  __safety: { toString: [Function] },
  domain: 
   { domain: null,
     _events: { error: [Function: handleException] },
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! minio@0.2.9 prepublish: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minio@0.2.9 prepublish script 'gulp test'.
npm ERR! This is most likely a problem with the minio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get their info via:
npm ERR!     npm owner ls minio
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\minio-js\npm-debug.log
```

**Comment by krishnasrinivas** [comment]
@harshavardhana after increasing the timeout if we are not seeing this issue we can close this.
