### ISSUE TITLE
unexpected behaviour in executing make-bucket.js example

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-js#377]
I am trying to execute: https://github.com/minio/minio-js/blob/master/examples/make-bucket.js  and below mentioned error i am getting.

```
$ node make-bucket.js

/source/minio.js:269
      throw new TypeError('region should be of type "string"')
            ^
TypeError: region should be of type "string"
    at Client.makeBucket (/source/minio.js:269:13)
    at Object.<anonymous> (/Users/koolhead17/minio-example-test/minio-JS/make-bucket.js:39:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by krishnasrinivas** [comment]
https://github.com/krishnasrinivas/minio-js/commit/2c83f54ac53e218e14dbbbb405d4222b339c9ffc
