### ISSUE TITLE
unexpected behaviour in executing put-object.js example

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-js#378]
I am trying to execute: https://github.com/minio/minio-js/blob/master/examples/put-object.js and below mentioned error i am getting.

```
$ node put-object.js

/source/minio.js:641
      throw new TypeError('stream should be a "Stream"')
            ^
TypeError: stream should be a "Stream"
    at Client.putObject (/source/minio.js:641:13)
    at /Users/koolhead17/minio-example-test/minio-JS/put-object.js:42:12
    at Object.oncomplete (fs.js:107:15)
```

**Comment by krishnasrinivas** [comment]
https://github.com/krishnasrinivas/minio-js/commit/2c83f54ac53e218e14dbbbb405d4222b339c9ffc
