### ISSUE TITLE
unexpected behaviour in executing presigned-getobject.js example

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-js#379]
I am trying to execute: https://github.com/minio/minio-js/blob/master/examples/presigned-getobject.js and below mentioned error i am getting.

```
$ node  presigned-getobject.js
undefined

/source/minio.js:251
          cb(null, region)
          ^
TypeError: undefined is not a function
    at /source/minio.js:890:7
    at DestroyableTransform.<anonymous> (/source/minio.js:251:11)
    at DestroyableTransform.emit (events.js:117:20)
    at /Users/koolhead17/github-dev/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
```

**Comment by krishnasrinivas** [comment]
fixed by https://github.com/krishnasrinivas/minio-js/commit/2c83f54ac53e218e14dbbbb405d4222b339c9ffc
