### ISSUE TITLE
function-tests failed on current master.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#437]
```
/source/s3-endpoints.js:36
    throw new TypeError(`Invalid region: ${region}`)
          ^
TypeError: Invalid region: undefined
    at getS3Endpoint (/source/s3-endpoints.js:36:11)
    at Client.getRequestOptions (/source/minio.js:154:25)
    at _makeRequest (/source/minio.js:340:29)
    at /source/minio.js:425:16
    at DestroyableTransform.<anonymous> (/source/minio.js:359:15)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at done (/Users/harsha/Repositories/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:195:19)
    at /Users/harsha/Repositories/minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:136:9
    at DestroyableTransform._flush (/source/transformers.js:47:7)
```

**Comment by krishnasrinivas** [comment]
fixed by 860c5ff28b03b893a8563b870960a94ff50402d4
