### ISSUE TITLE
Working with node v6.6.0 throws `Minio is not a constructor` Error

### ISSUE THREAD

**Issue by martianyi** [minio/minio-js#499]
The latest version(2.0.2) of minio js is not working with node v6.6.0, working fine with node v6.5.0 though. I'm not sure what the reason is.

```
2016-09-18 16:11:50:[31merror[39m: uncaughtException: Minio is not a constructor date=Sun Sep 18 2016 08:11:50 GMT+0000 (UTC), pid=53, uid=0, gid=0, cwd=/usr/src/app, execPath=/usr/local/bin/node, version=v6.6.0, argv=[/usr/local/bin/node, /usr/src/app/bin/www], rss=76034048, heapTotal=70139904, heapUsed=38747832, loadavg=[1.07958984375, 1.04052734375, 0.6455078125], uptime=538426, trace=[column=21, file=/usr/src/app/lib/minio-client.js, function=, line=6, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=565, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=483, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=21, file=/usr/src/app/lib/storyline-server.js, function=, line=6, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=565, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=483, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false], stack=[TypeError: Minio is not a constructor, at Object.<anonymous> (/usr/src/app/lib/minio-client.js:6:21), at Module._compile (module.js:556:32), at Object.Module._extensions..js (module.js:565:10), at Module.load (module.js:473:32), at tryModuleLoad (module.js:432:12), at Function.Module._load (module.js:424:3), at Module.require (module.js:483:17), at require (internal/module.js:20:19), at Object.<anonymous> (/usr/src/app/lib/storyline-server.js:6:21), at Module._compile (module.js:556:32), at Object.Module._extensions..js (module.js:565:10), at Module.load (module.js:473:32), at tryModuleLoad (module.js:432:12), at Function.Module._load (module.js:424:3), at Module.require (module.js:483:17), at require (internal/module.js:20:19)]
2016-09-18 16:11:50:
2016-09-18 16:11:50:/usr/src/app/lib/minio-client.js:6
2016-09-18 16:11:50:const minioClient = new Minio({
2016-09-18 16:11:50: ^
2016-09-18 16:11:50:TypeError: Minio is not a constructor
2016-09-18 16:11:50: at Object.<anonymous> (/usr/src/app/lib/minio-client.js:6:21)
2016-09-18 16:11:50: at Module._compile (module.js:556:32)
2016-09-18 16:11:50: at Object.Module._extensions..js (module.js:565:10)
2016-09-18 16:11:50: at Module.load (module.js:473:32)
2016-09-18 16:11:50: at tryModuleLoad (module.js:432:12)
2016-09-18 16:11:50: at Module.require (module.js:483:17)
2016-09-18 16:11:50: at require (internal/module.js:20:19)
2016-09-18 16:11:50: at Object.<anonymous> (/usr/src/app/lib/storyline-server.js:6:21)
2016-09-18 16:11:50: at Object.Module._extensions..js (module.js:565:10)
2016-09-18 16:11:50: at Module.load (module.js:473:32)
2016-09-18 16:11:50: at Function.Module._load (module.js:424:3)
2016-09-18 16:11:50: at require (internal/module.js:20:19)
```

**Comment by krishnasrinivas** [comment]
@martianyi thanks for reporting this, we recently changed the API, need to update the docs, can you try doing this:

`const minioClient = new Minio.Client({...})`

**Comment by martianyi** [comment]
Hi，thanks for reply,  I was using it like that, only the options were reading from another confit.json file,  I'm not sure if node v6.6.0 has changed its mechanism so I couldn't read these options, I'll check my related functions again tomorrow.

**Comment by krishnasrinivas** [comment]
can you post your source @martianyi ?

**Comment by martianyi** [comment]
OK, this is the code to read and export configs, it will read the runtime.json file in the same folder and export configs["RUNTIME"]["MINIO_ACCESS_TOKEN"] etc.
<pre>
"use strict";

/**
 * remove comments in json files and export them under configs.
 */
const fs = require('fs');
const path = require('path');
const removeComment = require('node-json-minify');
const basename = path.basename(module.filename); // =>index.js

let configs = {};

fs
    .readdirSync(__dirname)
    .filter(function (file) {
        return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-5) === '.json');
    })
    .forEach(function (file) {
        let name = file.split('.').shift().toUpperCase(); // =>'ENVIRONMENT','ENGINE','RUNTIME'
        configs[name] = JSON.parse(removeComment(fs.readFileSync(path.join(__dirname, file), 'utf8')));
    });

module.exports = configs;
</pre>
 
And this is the minioClient code

<pre>
"use strict";

const configs = require('../configs');
const Minio = require('minio');

const minioClient = new Minio({
    endPoint: configs['RUNTIME']['MINIO_ENDPOINT'],
    accessKey: configs['RUNTIME']['MINIO_ACCESS_KEY'],
    secretKey: configs['RUNTIME']['MINIO_SECRET_KEY']
});

module.exports = minioClient;
</pre>

With node 6.5.0 these work fine, but throw error with node 6.6.0

**Comment by martianyi** [comment]
Ah, I know the problem, I should use Minio.Client, sorry I didn't see your reply clearly. This issue could close then.
