### ISSUE TITLE
Error Uploading to Minio if objectName contains forward slash

### ISSUE THREAD

**Issue by sachinwalia2k8** [minio/minio-js#520]
I am using minio-js to upload local processed to Minio and want to ensure that objectName follows a certain path hierarchy. Whenever I upload without any forward slash it works fine but when it has any forward slash it fails with following error:

FYI, objectName has following format:

`img001/req001/compressed/IMG01.jpeg
`
```
8:59:16 AM - error: [req001] Error occurred while processing request::S3Error: We encountered an internal error, please try again.
    at Object.parseError (/source/xml-parsers.js:58:11)
    at /source/transformers.js:113:23
    at DestroyableTransform._flush (/source/transformers.js:49:10)
    at DestroyableTransform.<anonymous> (/java/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at finishMaybe (/java/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/java/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (/java/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at IncomingMessage.onend (_stream_readable.js:511:10)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by sachinwalia2k8** [comment]
I must mention that downloading object with name of format below works fine. `img001/req001/compressed/IMG01.jpeg`
I'd appreciate any help.

**Comment by harshavardhana** [comment]
Object name cannot have a forward slash on Minio

**Comment by sachinwalia2k8** [comment]
@harshavardhana - is there any way you can store path information if you want to maintain a hierarchy?

**Comment by harshavardhana** [comment]
> @harshavardhana - is there any way you can store path information if you want to maintain a hierarchy?

You should always upload with a path i.e for example if you have an object locally and you wish to create a hierarchy it is as simple as.

```
mc cp /etc/issue.net myminio/testbucket/1/2/3/4/5/
```

Here mc PUT's an object with resource as `/testbucket/1/2/3/4/5/issue.net`

**Comment by sachinwalia2k8** [comment]
So does that mean the path information should be as part of bucket

**Comment by harshavardhana** [comment]
> So does that mean the path information should be as part of bucket

A path comprises of a 'bucket' and an object

Here the 'testbucket' is the bucket and '1/2/3/4/5/issue.net' is the object. For a URL resource it becomes 

'/testbucket/1/2/3/4/5/issue.net' 

Now you have an object which needs to be created at a specific location you need to provide the entire hierarchy, there is no reason to create a directory skeletal first and then upload an object into it.  You can do that by avoiding one unnecessary call to create an object with "/".

Object storage shouldn't be treated like POSIX in posix it is necessary to do "mkdir" first and then copy the file inside the directory.

**Comment by krishnasrinivas** [comment]
@harshavardhana i think the object name under consideration does not have a trailing `/` i.e `img001/req001/compressed/IMG01.jpeg` is a valid object name, or is there any other detail I am missing?

@sachinwalia2k8 can you post a sample test script that we can run and reproduce the problem?

**Comment by sachinwalia2k8** [comment]
@krishnasrinivas - Sorry I forgot to update the ticket. The problem seems to be the permission issue with the minio user not able to create directories inside the bucket on my Linux machine. After granting the appropriate permission the issue cease to exit.
