### ISSUE TITLE
functional tests not running against play.minio.io

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#548]
```
46 passing (37s)
  4 failing

  1) functional tests presigned operations should upload using presinged POST:
     Error: socket hang up
      at createHangUpError (_http_client.js:252:15)
      at TLSSocket.socketOnEnd (_http_client.js:344:23)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) functional tests presigned operations should upload using presinged POST:
     Error: socket hang up
      at createHangUpError (_http_client.js:252:15)
      at TLSSocket.socketOnEnd (_http_client.js:344:23)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  3) functional tests listObjects should list objects using v2 api:
     Error: listObjects lists 20 objects, expected 10
      at Readable.<anonymous> (dist/test/functional-tests.js:560:25)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  4) functional tests "after all" hook:
     Uncaught AssertionError: assert.fail()
      at dist/main/notification.js:169:18
      at Array.forEach (native)
      at .<anonymous> (dist/main/notification.js:168:19)
      at readableAddChunk (_stream_readable.js:176:18)
      at Readable.push (_stream_readable.js:134:10)
      at Transform.push (_stream_transform.js:128:32)




events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: 4 tests failed.
error Command failed with exit code 7.
```

We need to investigate why only few tests are failing.

**Comment by harshavardhana** [comment]
Looks like same with s3 as well 

```

  3) functional tests listObjects should list objects using v2 api:
     Error: listObjects lists 20 objects, expected 10
      at Readable.<anonymous> (dist/test/functional-tests.js:560:25)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by harshavardhana** [comment]
can you take a look at this @krishnasrinivas ? - listObjectsV2 API is not working correctly.

**Comment by krishnasrinivas** [comment]
checking
