### ISSUE TITLE
callback should be of type "function"

### ISSUE THREAD

**Issue by halfcrazy** [minio/minio-js#549]
In my test code, i'm confusing why there is always a callback should be of type function err.
I'm sure my param is a function.

minio@^3.1.1

```
/Users/halfcrazy/workspace/skylar-CI-framework/skylar_castle/server/node_modules/minio/dist/main/minio.js:781
      throw new TypeError('callback should be of type "function"')
            ^
TypeError: callback should be of type "function"
    at Client.getPartialObject (/Users/halfcrazy/workspace/skylar-CI-framework/skylar_castle/server/node_modules/minio/dist/main/minio.js:781:13)
    at /Users/halfcrazy/workspace/skylar-CI-framework/skylar_castle/server/node_modules/minio/dist/main/minio.js:720:16
    at FSReqWrap.oncomplete (fs.js:111:15)
```

```js
s3obj.js
import * as Minio from 'minio';
import { Promise } from 'bluebird';

import workerConf from '../config/worker.conf';

const minioClient = new Minio.Client(workerConf['minio']);

export const fGetObj = async (bucket, fname, dst) => {
  return new Promise((resolve, reject) => {
    minioClient.fGetObject(bucket, fname, dst, (err) => {
      if (err) {
        console.log(err)
        reject(err);
      }
      resolve(dst);
    });
  });
};

export const fPutObj = async (dst, src) => {

};
```

```js
test.js
var s3obj = require('./utils/s3obj');

s3obj.fGetObj('smoketest', '1486713318283.zip', './haha.zip')
  .then(function(dst){console.log(dst)})
  .catch(function(err){console.log(err)});
```

**Comment by harshavardhana** [comment]
Looks like a bug @halfcrazy . We will fix it.

**Comment by halfcrazy** [comment]
@harshavardhana If this has been solved, when will it be released, publish to npm?

**Comment by harshavardhana** [comment]
> @harshavardhana If this has been solved, when will it be released, publish to npm?

Soon @halfcrazy
