### ISSUE TITLE
Certain endpoints don't work

### ISSUE THREAD

**Issue by luhkevin** [minio/minio-js#562]
I was testing out different endpoints in your constructor and they don't all work:

```
> var play = new Minio.Client({endPoint: 'https://play.minio.io:9000', port:9000, secure: false, accessKey: 'myaccesskey', secretKey: 'mysecretkey'})
InvalidEndpointError: endPoint https://play.minio.io:9000 is invalid
    at new Client (/opt/app/myapp/node_modules/minio/dist/main/minio.js:67:13)
    at repl:1:12
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
```

**Comment by krishnasrinivas** [comment]
https://docs.minio.io/docs/javascript-client-quickstart-guide

you have to use:
```
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'play.minio.io',
    port: 9000,
    secure: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});
```

**Comment by krishnasrinivas** [comment]
@luhkevin closing this, let us know if the documentation anywhere shows you any incorrect infomation.

**Comment by luhkevin** [comment]
https://docs.minio.io/docs/javascript-client-api-reference
In the "Constructor" documentation, it says:

```
endPoint is an URL, domain name, IPv4 address or IPv6 address.Valid endpoints are listed below:
https://s3.amazonaws.com
https://play.minio.io:9000
localhost
play.minio.io
```

I think the docs are out of date?
So, if I'm understanding correctly, your "endpoint" field supports a "host"? It doesn't take protocol or port?

**Comment by krishnasrinivas** [comment]
@luhkevin documentation will be fixed: https://github.com/minio/minio-js/pull/563

Thanks for bringing this to our notice.
