### ISSUE TITLE
Mint failing on gateway azure list objects

### ISSUE THREAD

**Issue by deekoder** [minio/minio-js#692]
https://github.com/minio/minio/pull/5889 
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-66f87a95-5171-4161-9a3a-739d0c3fe0ce, recursive:false",
  "duration": 184,
  "status": "FAIL",
  "error": "Error: listObjects lists 11 objects, expected 10 at Readable.client.listObjects.on.on (test/functional-tests.js:947:23) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Exe

**Comment by deekoder** [comment]
Marking high as they are blocking PR merging for next release.

**Comment by deekoder** [comment]
filed here incorrectly instead of minio/minio
