### ISSUE TITLE
Error while running Azure tests on Mint

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio-js#703]
While running the Azure gateway tests for minio-js, I got the following error:
```
{
  "name": "minio-js",
  "function": "statObject(bucketName, objectName, cb)",
  "args": "bucketName:minio-js-test-b5d810a9-3b91-4122-8b0a-2aa7ad3240f9, objectName:datafile-100-kB",
  "duration": 74,
  "status": "FAIL",
  "error": "Error: content-type mismatch at client.statObject (test/functional-tests.js:449:93) at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:1396:7 at ClientRequest.<anonymous> (node_modules/minio/dist/main/minio.js:416:36) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:478:21) at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) at Socket.socketOnData (_http_client.js:367:20) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)"
}
```

**Comment by kannappanr** [comment]
Fixed by https://github.com/minio/minio/pull/6061
