### ISSUE TITLE
functional tests wrongly execute S3 specific tests on .amazonaws.com endpoint

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#709]
```
 docker run --rm -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e MINT_MODE=full -e SERVER_ENDPOINT=qumulo-nas-lb-1906730632.us-west-2.elb.amazonaws.com:9000 -e ENABLE_HTTPS=0 minio/mint:edge minio-js
Running with
SERVER_ENDPOINT:      qumulo-nas-lb-1906730632.us-west-2.elb.amazonaws.com:9000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fa3e797452d3:/mint/log /tmp/mint-logs'
(1/1) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "removeBucket(bucketName)",
  "args": "bucketName:minio-js-test-84335dd2-2c33-4675-930a-d3f83312f272-region",
  "duration": 91,
  "status": "FAIL",
  "error": "S3Error: The specified bucket does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 0 out of 1 tests successfully.
```

**Comment by kanagarajkm** [comment]
@harshavardhana  I ran the tests against a minio server running in `ec2-52-53-149-131.us-west-1.compute.amazonaws.com`, but the test is not failing. can you please check.

```
docker run --rm -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e MINT_MODE=full -e SERVER_ENDPOINT=ec2-52-53-149-131.us-west-1.compute.amazonaws.com:9000 -e 
Running with
SERVER_ENDPOINT:      ec2-52-53-149-131.us-west-1.compute.amazonaws.com:9000
ACCESS_KEY:           YR8IL25PXM8PE5RLE2ND
SECRET_KEY:           ***REDACTED***      
ENABLE_HTTPS:         0                 
SERVER_REGION:        us-east-1                    
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
               
To get logs, run 'docker cp 7c4adadad012:/mint/log /tmp/mint-logs'
                               
(1/1) Running minio-js tests ... done in 2 minutes and 40 seconds
                                                                                                                                  
All tests ran successfully                        
```

**Comment by harshavardhana** [comment]
This looks fixed.. closing
