### ISSUE TITLE
Content-Language metadata in functional tests are invalid for GCS backend

### ISSUE THREAD

**Issue by jefvel** [minio/minio-js#766]
Currently the `Content-Language` header is set to `123` in the functional tests. When using GCS as a backend, the test will fail:
 ```
{
  "name": "minio-js",
  "function": "putObject(bucketName, objectName, stream, metaData, cb)",
  "args": "bucketName:minio-js-test-55bfb999-e200-432c-bb72-4fc0194f73c7, objectName:datafile-100-kB, stream: 100kb, metaData:[object Object]",
  "duration": 1426,
  "status": "FAIL",
  "error": "S3Error: The specified key does not exist. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:56:11) at /home/jefvel/minio-js/minio-js/minttestjs/node_modules/minio/dist/main/transformers.js:117:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:48:26) at DestroyableTransform.<anonymous> (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12) at finishMaybe (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12) at endWritable (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3) at DestroyableTransform.Writable.end (node_modules/minio/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5) at IncomingMessage.onend (_stream_readable.js:598:10) at endReadableNT (_stream_readable.js:1054:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)"
}
```

As seen here, only `ISO 639-1` language codes are accepted: https://cloud.google.com/storage/docs/metadata#content-language

It should be changed to a valid value, for example `en`

**Comment by kannappanr** [comment]
@jefvel Thanks for the PR, we have merged #768, so closing this issue.
