### ISSUE TITLE
Getting type error

### ISSUE THREAD

**Issue by kishore0709** [minio/minio-js#781]
I'm using below script to upload objects to s3 bucket, but getting type error.
Please help resolev the issue. Thanks!
```
**Error:**
[root@xxxx~]# node put-object.js
/root/put-object.js:8
var s3Client = new Minio({
               ^

**TypeError: Minio is not a constructor
    at Object.<anonymous> (/root/put-object.js:8:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
[root@xxx~]# vim put-object.js**
---------------------

**Script:**

var Minio = require('minio')
var fs = require('fs')

// find out your s3 end point here:
// http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

var s3Client = new Minio({
  url: 'https://<your-s3-endpoint>',
  accessKey: 'YOUR-ACCESSKEYID',
  secretKey: 'YOUR-SECRETACCESSKEY'
})

var outFile = fs.createWriteStream('your_localfile.zip');
var fileStat = Fs.stat(file, function(e, stat) {
  if (e) {
    return console.log(e)
  }
  s3Client.putObject('mybucket', 'hello/remote_file.zip', 'application/octet-stream', stat.size, fileStream, function(e) {
    return console.log(e) // should be null
  })
})
```

**Comment by kannappanr** [comment]
Please take a look at `minio-js` examples here https://github.com/minio/minio-js/tree/master/examples

Please also look at the documentation at https://docs.min.io/docs/javascript-client-api-reference.html

Here is an example that will work

```
var Minio = require('minio')
var Fs = require('fs')

var s3Client = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: false,
  accessKey: 'minio',
  secretKey: 'minio123'
})

var file = '/etc/issue'
s3Client.fPutObject('my-bucketname', 'my-objectname', file, function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("Success")
})

```
Closing the issue now. Please reach out to us at https://slack.min.io for such questions.
