### ISSUE TITLE
originalname meta with utf-8 symbols

### ISSUE THREAD

**Issue by egmen** [minio/minio-js#802]
This code

```javascript
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});

var meta = { originalname: 'тест.pdf' };

minioClient.putObject('test', 'test.pdf', Buffer.from(''), 0, meta)
```
throws error
```
_http_outgoing.js:464
    throw err;
    ^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-amz-meta-originalname"]
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:194:14)
    at Object.request (https.js:289:10)
    at _makeRequest (C:\Projects\aclub-bpm\node_modules\minio\dist\main\minio.js:501:36)
    at DestroyableTransform.<anonymous> (C:\Projects\aclub-bpm\node_modules\minio\dist\main\minio.js:562:11)
    at DestroyableTransform.emit (events.js:203:15)
    at endReadableNT (C:\Projects\aclub-bpm\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by egmen** [comment]
I've fixed it locally like this:
```javascript
var querystring = require('querystring')
...
var meta = { originalname: querystring.escape('тест.pdf') };
```

**Comment by kannappanr** [comment]
@egmen Thanks for reporting this issue. We will fix it on our end.

**Comment by Praveenrajmani** [comment]
@egmen The SDK should not try to encode the headers. aws sdk fails with the same error. 

```
var AWS = require('aws-sdk');

var s3  = new AWS.S3({
    accessKeyId: 'minio' ,
    secretAccessKey: 'minio123' ,
    endpoint: 'http://127.0.0.1:9000' ,
    s3ForcePathStyle: true, // needed with minio?
    signatureVersion: 'v4'
});

// putObject operation.

var params = {Bucket: 'testb', Key: 'testobject', Body: 'Hello from MinIO!!', Metadata: {
    'x-amz-meta-my-key': 'тест.pdf',
}};

s3.putObject(params, function(err, data) {
    if (err)
        console.log(err)
    else   
        console.log("Successfully uploaded data to testbucket/testobject");
});

```

So, the work around is to escape/unescape from the user end.

**Comment by Praveenrajmani** [comment]
We can close this issue @kannappanr

**Comment by kannappanr** [comment]
closing this issue based on the above comments. Please feel free to reach out to us if you have further questions

**Comment by lukepolo** [comment]
it would be nice if the error was catchable

```

  public createStream(filename: string): Writable {
    const passThrough = new PassThrough();

    this.client.putObject(this.bucket, filename, passThrough, (error) => {
      if (error) {
        passThrough.emit("error", error);
      }
      passThrough.emit("close");
    });

    passThrough.on("error", () => {
      logger.info("SHIT")
    })

    return passThrough;
  }
  ```

**Comment by prakashsvmx** [comment]
The callback has the error if only the call fails. 
So
```
if (err)
{
        console.log(err)
// May be you can( re )throw with a wrapped function
}

    else   {
        console.log("Successfully uploaded data to testbucket/testobject");

}
```

**Comment by lukepolo** [comment]
yah for some reason it doesn't get into the callback , feel free to try it yourself as well~
