### ISSUE TITLE
filepath with backslash

### ISSUE THREAD

**Issue by egmen** [minio/minio-js#803]
NodeJS 10 on Windows, Minio server on Linux.
This code example:
```javascript
var Minio = require('minio')
var path = require('path')

var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});

let filePath = path.join('a', 'test.pdf')
// filePath = filePath.replace(/\\/g, '/')
console.log({ filePath })

minioClient.putObject('test', filePath, Buffer.from(''), 0, (err) => {
  if (err) console.error(err)
})
```
throws error
```javascript
{ filePath: 'a\\test.pdf' }
{ S3Error: Object name contains unsupported characters.
    at Object.parseError (C:\Projects\aclub-bpm\node_modules\minio\dist\main\xml-parsers.js:83:11)
    at C:\Projects\aclub-bpm\node_modules\minio\dist\main\transformers.js:153:22
    at DestroyableTransform._flush (C:\Projects\aclub-bpm\node_modules\minio\dist\main\transformers.js:77:10)
    at DestroyableTransform.prefinish (C:\Projects\aclub-bpm\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (C:\Projects\aclub-bpm\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Projects\aclub-bpm\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Projects\aclub-bpm\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:\Projects\aclub-bpm\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at IncomingMessage.onend (_stream_readable.js:655:10)
  code: 'XMinioInvalidObjectName',
  key: 'a\\test.pdf',
  bucketname: 'test',
  resource: '/test/a\\test.pdf',
  region: 'us-east-1',
  requestid: '15C7F93B07D4A023',
  hostid: '6faeded5-5cf3-4133-8a37-07c5d500207c',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null }
```
Could you fix it in a library (maybe on server) or I should write a code, which depends on target OS?

**Comment by kannappanr** [comment]
@egmen Will take a look and fix it at the appropriate place. Thanks for reporting the issue

**Comment by sinhaashish** [comment]
If you are using `path.join` then this itself means that it is dependent on OS .
Refer : https://nodejs.org/api/path.html#path_path_join_paths
This states `The path.join() method joins all given path segments together using the platform-specific separator as a delimiter, then normalizes the resulting path.` 

Example: `path.join('a','b')` gives the o/p as 
``` 
window : a\\b
Linux : a/b
```
In order to solve this you should be using something like `["a", "b"].join("/")` 
This will give o/p as `a/b` and the request wont fail.
 For `\\` in key ; server will respond with `XMinioInvalidObjectName`  as it does not support `\` in the object name .
 Refer https://github.com/minio/minio/blob/master/docs/minio-limits.md#object-name-restrictions-on-minio

**Comment by egmen** [comment]
Thx!
I've read about original S3 API https://docs.aws.amazon.com/en_us/AmazonS3/latest/dev/UsingMetadata.html
There is also such restriction.
