### ISSUE TITLE
Signature Error

### ISSUE THREAD

**Issue by erikburt** [minio/minio-js#812]
### Problem
I'm getting a signing error when using this library (v7.0.12). It happens on both function calls I've tested it with, `fGetObject` and `presignedGetObject`.

### Environment
Minio server is running locally in docker and the image is up-to-date.

I've tested this both on my machine running Windows 10 and inside of a docker container running the up-to-date `node:10` image (debian 9) and both environments produce the same error. I'm running other services and the python Minio client is working fine so I'm guessing the problem is on this end.

### Config
Inside my client configuration I have `useSSL: false`, I get a different error if it's set to `true` but that's likely because I don't have any generated or signed certificates.

### Stack Trace 
```
S3Error: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Object.parseError (C:\<user_path>\node_modules\minio\dist\main\xml-parsers.js:83:11)
    at C:\<user_path>\node_modules\minio\dist\main\transformers.js:153:22
    at DestroyableTransform._flush (C:\<user_path>\node_modules\minio\dist\main\transformers.js:77:10)
    at DestroyableTransform.prefinish (C:\<user_path>\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (C:\<user_path>\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\<user_path>\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\<user_path>\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:\<user_path>\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at IncomingMessage.onend (_stream_readable.js:671:10)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by kannappanr** [comment]
@erikburt Are you seeing this issue when you run it against Play?

I tested the following code against `play`, `s3` and `local minio` it works everywhere. Version tested was `7.0.12`

```
var Minio = require('/tmp/nd/node_modules/minio/dist/main/minio')

var s3Client = new Minio.Client({
  endPoint: 'play.min.io',
  accessKey: 'Q3AM3UQ867SPQQA43P2F',
  secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
  port: 9000,
  useSSL: true
})

// Get a full object.
s3Client.fGetObject('test', 'issue', '/tmp/objfile', function(e) {
  if (e) {
    return console.log(e)
  }
  console.log('done')
})
```

If you can paste a sample code we can take a look at let you know.

**Comment by erikburt** [comment]
I'll test this out on Monday when I have access to my work computer.
