### ISSUE TITLE
Getting InvalidBucketNameError even when the bucket name is correct

### ISSUE THREAD

**Issue by vibrantrida** [minio/minio-js#852]
I am receiving an `InvalidBucketNameError` even when the bucket name is correct.
```js
const Minio = require('minio')

const mc = new Minio.Client({
  accessKey: 'minioadmin',
  secretKey: 'minioadmin',
  endPoint: 'localhost',
  port: 9000,
  useSSL: false
})

const params = {
  bucketName: 'localbucket'
}

const stream = mc.listObjectsV2(params.bucketName)
stream.on('data', (obj) => {
  console.log(JSON.stringify(obj, null, 2))
})
stream.on('error', (err) => console.error(err))
```
```
F:\BACKUP\sandbox\nodejs\minio-test\node_modules\minio\dist\main\minio.js:1644
        throw new errors.InvalidBucketNameError('Invalid bucket name: ' + bucketName);
        ^
InvalidBucketNameError: Invalid bucket name: localbucket
    at Client.listObjectsV2 (F:\BACKUP\sandbox\nodejs\minio-test\node_modules\minio\dist\main\minio.js:1644:15)
    at Object.<anonymous> (F:\BACKUP\sandbox\nodejs\minio-test\minio.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

`localbucket` is one of the results in `listBuckets`:
```
[
  {
    "name": "localbucket",
    "creationDate": "2020-05-06T01:40:46.287Z"
  },
  // ...
  {
    "name": "videos",
    "creationDate": "2020-02-10T23:19:07.902Z"
  }
]
```
I also made sure to set the bucket's policy to public.

Any ideas why this is happening?

**Comment by kannappanr** [comment]
@vibrantrida You do not have to set the bucket policy to public. I tried your code against `play` and that worked fine.

I would probably try something like

```
const Minio = require('minio')

function isString(arg) {
  return typeof(arg) === 'string'
}

function isValidBucketName(bucket) {
  if (!isString(bucket)) return false

  // bucket length should be less than and no more than 63
  // characters long.
  if (bucket.length < 3 || bucket.length > 63) {
    return false
  }
  // bucket with successive periods is invalid.
  if (bucket.indexOf('..') > -1) {
    return false
  }
  // bucket cannot have ip address style.
  if (bucket.match(/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/)) {
    return false
  }
  // bucket should begin with alphabet/number and end with alphabet/number,
  // with alphabet/number/.- in the middle.
  if (bucket.match(/^[a-z0-9][a-z0-9.-]+[a-z0-9]$/)) {
    return true
  }
  return false
}



const params = {
  bucketName: 'localbucket'
}

console.log(isValidBucketName(params.bucketName))

const mc = new Minio.Client({
  accessKey: 'minio',
  secretKey: 'minio123',
  endPoint: 'play.min.io',
  port: 80,
  useSSL: false
})


const stream = mc.listObjectsV2(params.bucketName)
stream.on('data', (obj) => {
  console.log(JSON.stringify(obj, null, 2))
})
stream.on('error', (err) => console.error(err))
``` 
to reproduce the issue and see why this is happening with your code.

**Comment by vibrantrida** [comment]
Thanks! though I have to say, validating bucket names is a good idea if multiple buckets are going to be used later but for this project only one bucket will be used so I find this unnecessary.

Any idea why this happens? it should work fine on a locally hosted min.io server like it did on the play server

**Comment by kannappanr** [comment]
Please take a look at this document from AWS S3 https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html where it clearly says that uppercase bucket names are not supported.

Closing this issue as answered. Please feel free to reach out to us t https://slack.min.io for further questions.

**Comment by MahendrenGanesan** [comment]
I had issue with tailing space
