### ISSUE TITLE
putObject returns error when `writeonly` policy is set

### ISSUE THREAD

**Issue by ofstudio** [minio/minio-js#857]
Source code
```js
//...
const minioClient = new Minio.Client({
  endPoint: 'my-minio.installation.url',
  port: 443,
  useSSL: true,
  accessKey: 'js1',
  secretKey: 'secret'
})


minioClient.putObject('test', 'test.gz', fileStream, function (err, etag) {
  if (err)
    console.log('Error: ', err)
  else
    console.log('Etag: ', etag)
})
```

If user `js` has `readwrite` policy everything is fine:
```bash
$ mc admin policy set server readwrite user=js1
Policy readwrite is set on user `js1`

$ node index
Etag:  799ecf7eb6fb05d7066a3469f71a43fd
```

But if the user  has `writeonly` policy an error occurs:
```sh
$ mc admin policy set server writeonly user=js1
Policy writeonly is set on user `js1`

$ node index
Error:  S3Error: Access Denied.
    at Object.parseError (/Users/oleg/Desktop/minio js/node_modules/minio/dist/main/xml-parsers.js:86:11)
    at /Users/oleg/Desktop/minio js/node_modules/minio/dist/main/transformers.js:156:22
    at DestroyableTransform._flush (/Users/oleg/Desktop/minio js/node_modules/minio/dist/main/transformers.js:80:10)
    at DestroyableTransform.prefinish (/Users/oleg/Desktop/minio js/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (events.js:315:20)
    at prefinish (/Users/oleg/Desktop/minio js/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/Users/oleg/Desktop/minio js/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/Users/oleg/Desktop/minio js/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/Users/oleg/Desktop/minio js/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (_stream_readable.js:677:10) {
  code: 'AccessDenied',
  bucketname: 'test',
  resource: '/test',
  requestid: '161D0C0B12D6A957',
  hostid: '35f38c72-111a-4d45-8a01-ac3e5912d22d',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

In both cases Minio Browser works as expected: full access with `readwrite` policy, and upload-only with `writeonly ` policy.

- Node v14.4.0
- minio-js v7.0.16
- minio-server v2020-06-22T03:12:50Z

**Comment by kannappanr** [comment]
Write only policy does not have getbucketlocation permission
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:PutObject"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
```
either you need to create a custom policy or you can set the region parameter in the constructor.

```
const minioClient = new Minio.Client({
  endPoint: 'my-minio.installation.url',
  port: 443,
  useSSL: true,
  accessKey: 'js1',
  secretKey: 'secret',
  region: 'us-east-1'
})
```
closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further questions.
