### ISSUE TITLE
minioClient.makeBucket is not a function

### ISSUE THREAD

**Issue by christianechevarria** [minio/minio-js#862]
Hi folks! I'm having what I believe to be a really simple issue that I'm just not seeing how to resolve. 

I'm using the JS client just as the README indicates

```javascript
// minio.js
let Minio = require('minio')

const minioClientConfig = {
  endPoint: process.env.MINIO_URI,
  port: parseInt(process.env.MINIO_PORT),
  useSSL: process.env.MINIO_HTTPS === 'true' ? true : false,
  accessKey: process.env.MINIO_ACCESS_KEY,
  secretKey: process.env.MINIO_SECRET_KEY,
}

const minioClient = new Minio.Client(minioClientConfig)

export default minioClient
```

```javascript
// index.js
const express = require('express')
const minioClient = require('./minio')

const app = express()

app.post('/test', async (req, res, next) => {
 
const { bucketId } = req.body  

try {
    const response = await minioClient.makeBucket(bucketId)

   return res.json({
      url: 'https://cheese.com',
    })
  } catch (e) {
    return next({
      msg: e,
    })
  }
})
```

but I'm getting this error

```bash
minioClient.makeBucket is not a function

  at api/index.js:44:40
  at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
  at next (node_modules/express/lib/router/route.js:137:13)
  at Route.dispatch (node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
  at node_modules/express/lib/router/index.js:281:22
  at Function.process_params (node_modules/express/lib/router/index.js:335:12)
  at next (node_modules/express/lib/router/index.js:275:10)
  at authorizationMiddleware (api/index.js:13:35)
  at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (node_modules/express/lib/router/index.js:317:13)
  at node_modules/express/lib/router/index.js:284:7
  at Function.process_params (node_modules/express/lib/router/index.js:335:12)
  at next (node_modules/express/lib/router/index.js:275:10)
  at node_modules/body-parser/lib/read.js:130:5
  at invokeCallback (node_modules/raw-body/index.js:224:16)
```

I've tried logging `minioClient` and this is what I get, there's no sign of any makeBucket function

```bash
{
  default: Client {
    transport: {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: hidden],
      validateHeaderValue: [Function: hidden],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    host: 'minio',
    port: 9000,
    protocol: 'http:',
    accessKey: 'REDACTED',
    secretKey: 'REDACTED',
    sessionToken: undefined,
    userAgent: 'MinIO (linux; x64) minio-js/7.0.16',
    anonymous: false,
    regionMap: {},
    partSize: 67108864,
    maximumPartSize: 5368709120,
    maxObjectSize: 5497558138880,
    enableSHA256: true,
    reqOptions: {}
  }
}
```

Any help would be appreciated, is there something glaringly obvious I'm missing?

**Comment by christianechevarria** [comment]
Update: I think this is a Docker related issue. Somehow within the container when `npm i` runs it pulls a types file for Minio instead of the actual library.

Closing for now since this is actually unrelated to Minio, I think

**Comment by christianechevarria** [comment]
Update (again): Just realized I was mixing CommonJS with built in JS module system :rofl: - that was my first mistake right there
