### ISSUE TITLE
TypeError: Cannot read property 'Client' of undefined

### ISSUE THREAD

**Issue by rupamking1** [minio/minio-js#950]
var Minio = require('minio')   working but
import Minio from 'minio';    not working 

// var Minio = require('minio')
import Minio from 'minio';

var s3Client = new Minio.Client({
  endPoint: 'play.min.io',
  port: 9000,
  useSSL: true,
  accessKey: 'Q3AM3UQ867SPQQA43P2F',
  secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});
var file = './aa.yml'

setTimeout(async () => {
  let up = await s3Client.fPutObject('aaaaa', 'aa.yml', file, { "metaData": "hk" })
  console.log(up)
}, 1);

**Comment by prakashsvmx** [comment]
Es6 modules are not supported. It would be gradually updated . Please feel free to send a PR.

**Comment by rupamking1** [comment]
Pls check this error, same problem in es6 & ES2019.

tsconfig.json-
{
  "compilerOptions": {
    "lib": ["es6", "dom"],
    "target": "es6",
}

TypeError: Cannot read property 'Client' of undefined
    at Object.<anonymous> (C:\node\Test.ts:83:26)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module._compile (C:\Users\uuic\AppData\Roaming\npm\node_modules\ts-node-dev\node_modules\source-map-support\source-map-support.js:547:25)
    at Module.m._compile (C:\Users\uuic\AppData\Local\Temp\ts-node-dev-hook-8624099781232535.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at require.extensions..jsx.require.extensions..js (C:\Users\uuic\AppData\Local\Temp\ts-node-dev-hook-8624099781232535.js:114:20)     
    at require.extensions.<computed> (C:\Users\uuic\AppData\Local\Temp\ts-node-dev-hook-8624099781232535.js:71:20)
    at Object.nodeDevHook [as .ts] (C:\Users\uuic\AppData\Roaming\npm\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
[ERROR] 09:21:31 TypeError: Cannot read property 'Client' of undefined

**Comment by prakashsvmx** [comment]
Please note:  Es6 modules are **NOT** supported

**Comment by hanumanjiblog** [comment]
Also es5 and es6 both makes error, 
Please correct this code & send how to to use typescript import for Minio.

> var Minio = require('minio') working but
> import Minio from 'minio'; not working
> 
> // var Minio = require('minio')
> import Minio from 'minio';
> 
> var s3Client = new Minio.Client({
> endPoint: 'play.min.io',
> port: 9000,
> useSSL: true,
> accessKey: 'Q3AM3UQ867SPQQA43P2F',
> secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
> });
> var file = './aa.yml'
> 
> setTimeout(async () => {
> let up = await s3Client.fPutObject('aaaaa', 'aa.yml', file, { "metaData": "hk" })
> console.log(up)
> }, 1);

**Comment by rupamking1** [comment]
Also es5 and es6 both makes error,
Please correct this code & send how to to use typescript import for Minio.



> var Minio = require('minio') working but
> import Minio from 'minio'; not working
> 
> // var Minio = require('minio')
> import Minio from 'minio';
> 
> var s3Client = new Minio.Client({
> endPoint: 'play.min.io',
> port: 9000,
> useSSL: true,
> accessKey: 'Q3AM3UQ867SPQQA43P2F',
> secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
> });
> var file = './aa.yml'
> 
> setTimeout(async () => {
> let up = await s3Client.fPutObject('aaaaa', 'aa.yml', file, { "metaData": "hk" })
> console.log(up)
> }, 1);

**Comment by wanpeng2008** [comment]
use import {Client} from 'minio' instead

**Comment by prakashsvmx** [comment]
Closing this as it is not a functional issue and more of a usage question.
