### ISSUE TITLE
setObjectTagging, removeObjectTagging errors on amazon aws s3

### ISSUE THREAD

**Issue by mobulaco** [minio/minio-js#964]
Hello,

Errors with tagging as direct aws s3 client how it works with play.min.io.

Everthing else that i tried also works on aws s3 account.

Thanks :)

**setObjectTagging with tagsMap = {"vuhu":"string"}**
S3Error: The Content-MD5 you specified did not match what we received.
    at Object.parseError (/root/projects/s3/node_modules/minio/dist/main/xml-parsers.js:89:11)
    at /root/projects/s3/node_modules/minio/dist/main/transformers.js:164:22
    at DestroyableTransform._flush (/root/projects/s3/node_modules/minio/dist/main/transformers.js:88:10)
    at DestroyableTransform.prefinish (/root/projects/s3/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (node:events:394:28)
    at prefinish (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (node:internal/streams/readable:693:10) {
  code: 'BadDigest',
  expecteddigest: 'PHkipudvWos3p1l4VwYI7A==',
  calculateddigest: 'lToqBRvV33vODwQRlq0v0A==',
  requestid: '0HQEMF911SAXB8M5',
  hostid: 'WbX/O5QZus0S1svBbmzW0MzVMNNotqTfQ7mesRwdyx8g62nQKRckDyNHF+xPD06HCOriHMVBKuM=',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}

**removeObjectTagging**

S3Error: 204
    at getError (/root/projects/s3/node_modules/minio/dist/main/transformers.js:146:15)
    at /root/projects/s3/node_modules/minio/dist/main/transformers.js:158:14
    at DestroyableTransform._flush (/root/projects/s3/node_modules/minio/dist/main/transformers.js:88:10)
    at DestroyableTransform.prefinish (/root/projects/s3/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (node:events:394:28)
    at prefinish (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/root/projects/s3/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (node:internal/streams/readable:693:10) {
  code: 'UnknownError',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}

**getObjectTagging**
Success [ { Key: 'addedfromawsconsole', Value: 'yes it is' } ]

**Comment by prakashsvmx** [comment]
Please add code block to replicate the issue.
We will investigate @mobulaco

**Comment by mobulaco** [comment]
Sure @prakashsvmx, 

The code is quite simple from tutorials :)

if you uncomment play.min.io block and comment other one, it works as expected.

`var Minio = require('minio')

/*var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});*/

var minioClient = new Minio.Client({
    endPoint: 's3.amazonaws.com',
    accessKey: 'xxx',
    secretKey: 'yyy'
});

var tagsMap = {"vuhu":"string"};
minioClient.setObjectTagging('mobulaco', 'test/test.log',tagsMap, function(err) {
  if (err) return console.log(err)
  console.log('File tagged successfully.')
});`


and for remove tag , it is almost same:

`var Minio = require('minio')

/*var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});*/

var minioClient = new Minio.Client({
    endPoint: 's3.amazonaws.com',
    accessKey: 'xxx',
    secretKey: 'yyy'
});

minioClient.removeObjectTagging('mobulaco', 'test/deneme.log', function(err, etag) {
  if (err) return console.log(err)
  console.log('File tags removed successfully.')
});`

Thanks.

**Comment by prakashsvmx** [comment]
@mobulaco  The fix is in : PR #968 . Please have a look.

**Comment by mobulaco** [comment]
@prakashsvmx I've tested (set tag, remove tags, get tags) on AWS S3 and it works perfectly. 

Thanks. :)
