### ISSUE TITLE
removeObjects Content-MD5 doesn't match (AWS S3)

### ISSUE THREAD

**Issue by mapleeit** [minio/minio-js#982]
```
S3Error: The Content-MD5 you specified did not match what we received.
    at Object.parseError (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/minio/dist/main/xml-parsers.js:89:11)
    at /Users/miaozhaofeng/Documents/jina/hubble/node_modules/minio/dist/main/transformers.js:164:22
    at DestroyableTransform._flush (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/minio/dist/main/transformers.js:88:10)
    at DestroyableTransform.prefinish (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (node:events:394:28)
    at DestroyableTransform.emit (node:domain:470:12)
    at prefinish (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/Users/miaozhaofeng/Documents/jina/hubble/node_modules/readable-stream/lib/_stream_writable.js:571:22) {
  code: 'BadDigest',
  expecteddigest: '7qVpUYEcWgm8BZ4fPyw/4g==',
  calculateddigest: 'KW8BVrK/pXJ3vqxiB4A7Ng==',
  requestid: '0H2Y7J2842HB24X1',
  hostid: 'JzwrnHUNTSTSqTacv4+Bj9bXwhhf3Gip6TspavQXvWDuaMgKzwTbuUKjPWLja9YVvdbyLPACbts=',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

Payload:

```
<Delete>
  <Quiet>true</Quiet>
  <Object>
    <Key>2co8kg94/61a72c17541a1a274e35f7fb.zip</Key>
  </Object>
</Delete>
```

Version: 7.0.23

**Comment by prakashsvmx** [comment]
https://github.com/minio/minio-js/pull/968 - has been up for review. you could try with that branch.

**Comment by mapleeit** [comment]
@prakashsvmx Thanks for your quick reply. Confirmed. With #968, it can work well. Looking forward to the new patch version.

**Comment by prakashsvmx** [comment]
Thank you for trying it out.
